# Base configs
baseurl: "https://bobm.photography"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-57L193T7CY"

# UI configs
title: "Photography by Bob Monteverde"
subtitle: ""
author: "Bob Monteverde"
header:
 title: "Photography"
 subtitle: "by Bob Monteverde"
footer:
 name: "Some Photography, By Bob Monteverde"
 bio: "I am a [Principal] Software Engineer, specializing in Front End and Data Visualization in d3.js, ReactJS, etc. While I am taking some time off, I've been learning photography."
 github: "While I have not allocated the time to build a unique site, I'll give credit where credit is due.  This site is a <a href=\"https://github.com/rampatra/photography\">fork of this repo by Ram Patra</a>."
#web_design: "AJ"

social_urls:
  linkedin: "www.linkedin.com/in/bobmonteverde"
  github: "https://www.github.com/monteverdebob"
  #twitter: ""
  #instagram: ""
  #dribbble: ""

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'